import assert from 'node:assert/strict';
import * as c from './public/core.js';
import {CHAPTERS,chapterConfig,advanceJourney} from './public/journey.js';
import {enemyPlan,naturalSpawn,spawnTrapEnemies,updateEnemies,castSpell,enemyDrops} from './public/enemies.js';
import {enemyLevelForFloor,population,floorRules,depthLoot,excavationCount,MUTATIONS} from './public/abyss-rules.js';
import {spawnDue,aliveCount} from './public/enemy-levels.js';
import {newAbyssRun,clearAbyssFloor,nextAbyssFloor,gateUnlocked,suspendAbyss,consumeCheckpoint,settleAbyss,floorRewardToken,chooseBoon,applyEvent} from './public/abyss-run.js';
import {newProgress,migrateProgress} from './public/save.js';
import {RELICS,rollRelic,appraisal,appraiseAll,workshop,loadoutStats,random,rarityOdds,relicDescription} from './public/relics.js';
import {ABYSS_GEAR,POWERS,MYTHICS,SYNERGIES,evolutionProgress} from './public/abyss-gear.js';
import {effectStats,strikeMultiplier,damageEffects,reviveEffects,killEffects,runtimeStats} from './public/gear-effects.js';
import {discover,discoverLoadout,codexEntries,synergyStatus} from './public/codex.js';
import {expeditionPlan,TRAP_TYPES,advanceTraps} from './public/expedition.js';
import {validProgress,competitiveScore} from './src/worker.js';
import {RevealSequence} from './public/reveal-sequence.js';
import {rollGrade,gradeScale,materialStrength,enchantOptions,fuseEquipment,exchangeRevival,consumeRevival,canRevive} from './public/equipment-crafting.js';
let passed=0;const test=(title,fn)=>{fn();console.log('PASS',title);passed++;};
const unlocked=()=>{const p=newProgress();p.floor=18;p.chapterStars['18']=1;p.abyss.unlocked=true;return p;};
const prepareRun=p=>Object.assign(newAbyssRun(p,1207),{hp:100,mp:60,light:100,seals:3,cleared:true,kills:0});
const findType=key=>RELICS.findIndex(r=>r.key===key&&r.abyss);
const gear=(key,seed=1)=>rollRelic(seed,2,0,{forcedType:findType(key),abyssFloor:99});
test('New powers append without reindexing v10 Mythics, and change actual combat state',()=>{
 assert.equal(findType('reincarnation'),92);assert.equal(findType('eater'),94);assert.equal(findType('twinstar'),96);assert.equal(RELICS.length,104);
 const s=effectStats({...loadoutStats(newProgress()),powers:['greedlamp','substitute','backlight'],curses:['madking']}),p={hp:100,mp:60,light:100,elapsed:40,effectState:{}};assert.equal(s.lightDrain,1.2);assert.equal(s.lootQuality,.25);assert.equal(damageEffects(s,p,1000,()=>1).damage,99);assert(damageEffects(s,p,1000,()=>1).damage>100);
 discoverLoadout(Object.assign(unlocked(),{inventory:[gear('twinstar')]}));
});
test('Grade scales affixes and material quality; four enchant slots multiply, consume once, and preserve protected items',()=>{
 for(const [f,g] of [[10,1],[30,2],[50,3],[70,4],[90,5]])assert.equal(rollGrade(f,()=>0,true),g);
 const low={...gear('blast',10),abyssGrade:1},high={...low,abyssGrade:5};assert(gradeScale(high)>gradeScale(low));assert(materialStrength(high)>materialStrength(low));assert(materialStrength(low)>materialStrength({tier:3}));
 const p=unlocked(),base=gear('blast',90);p.inventory=[base];p.equipped[0]=base.id;
 for(let n=0;n<4;n++){const m={...gear('chain',100+n),abyssGrade:5};p.inventory.push(m);const options=enchantOptions(m,RELICS),at=options.findIndex(e=>e.key==='enemy'+m.type%6);assert(!fuseEquipment(p,base.id,m.id,at,-1,RELICS).error);assert(!p.inventory.some(i=>i.id===m.id));assert(fuseEquipment(p,base.id,m.id,at,-1,RELICS).error);}
 assert.equal(base.enchants.length,4);const multiplier=loadoutStats(p).enemyMultipliers[findType('chain')%6];assert(Math.abs(multiplier-Math.min(3,Math.pow(1.355,4)))<1e-9);
 const m=gear('corpse',22);p.inventory.push(m);const at=enchantOptions(m,RELICS).findIndex(e=>e.power==='corpse');assert(fuseEquipment(p,base.id,m.id,at,-1,RELICS).error);m.favorite=true;assert(fuseEquipment(p,base.id,m.id,at,0,RELICS).error);m.favorite=false;assert(!fuseEquipment(p,base.id,m.id,at,0,RELICS).error);assert(loadoutStats(p).powers.includes('corpse'));assert(!loadoutStats(p,true).powers.includes('corpse'));assert(validProgress(p));const reloaded=migrateProgress(JSON.parse(JSON.stringify(p)));assert.deepEqual(reloaded.inventory[0].enchants,base.enchants);base.enchants.push(base.enchants[0]);assert(!validProgress(p));
});
test('Revival exchange costs exact owned unprotected equipment, revives only three times and survives checkpoint reload',()=>{
 for(const [tier,cost] of [[3,10],[4,8],[5,3]]){const p=unlocked();p.inventory=Array.from({length:cost},(_,n)=>tier===3?rollRelic(n+90,0,0,{forcedType:18}):gear(tier===4?'blast':'eater',n+200));const ids=p.inventory.map(i=>i.id);assert(exchangeRevival(p,[...ids,ids[0]]).error);p.inventory[0].favorite=true;assert(exchangeRevival(p,ids).error);p.inventory[0].favorite=false;assert(!exchangeRevival(p,ids).error);assert.equal(p.inventory.length,0);assert.equal(p.abyss.revivalStock,1);assert(exchangeRevival(p,ids).error);assert(validProgress(p));}
 const p=unlocked();p.abyss.revivalStock=8;const run=prepareRun(p),player={hp:0,mp:0,light:0,lightMax:100,poisonUntil:99},stats=loadoutStats(p);for(let n=0;n<3;n++){assert(canRevive(run));assert(consumeRevival(p,run,player,stats));assert.equal(player.hp,70);assert.equal(player.light,60);assert.equal(player.poisonUntil,0);assert.equal(run.revivals,n+1);}assert(!consumeRevival(p,run,player,stats));assert.equal(p.abyss.revivalStock,5);assert.equal(run.reviveUsed,false);assert(suspendAbyss(p,run));assert(validProgress(p));const q=migrateProgress(JSON.parse(JSON.stringify(p))),resumed=consumeCheckpoint(q);assert.equal(resumed.revivals,3);assert(!canRevive(resumed));
});
test('Bonus floors are safe across every spawn path; boss floors stock extra LIGHT; Mythic begins at 80F with 5% odds',()=>{
 for(const f of [25,50,75,99]){c.generateStage(1900+f,18,1,false,{abyssFloor:f,route:'hunt',mutators:['horde','night']});const rules=floorRules(f),enemies=enemyPlan(20);assert.equal(enemies.length,0);assert.equal(spawnTrapEnemies(enemies,c.START,3).length,0);assert.equal(naturalSpawn(enemies,c.START,20).length,0);assert.equal(spawnDue({},1000,rules,enemies),0);assert.equal(expeditionPlan().traps.length,0);assert.equal(rules.light,0);assert.equal(rules.bonusCount,({25:1,50:2,75:3,99:1})[f]);const run=prepareRun(unlocked());run.floor=f;const token=floorRewardToken(run);assert.equal(token.minTier,4);assert.equal(!!token.mythic,f===99);assert.equal(floorRewardToken(run),null);}
 c.generateStage(900,18,1,false,{abyssFloor:9});const ordinary=c.orbPlan();c.generateStage(900,18,1,false,{abyssFloor:10});assert(c.orbPlan().length>ordinary.length*2);assert(c.orbPlan().every(o=>o.amount>=28));
 for(let f=1;f<=99;f++)assert.equal(depthLoot(f).mythic,f>=80?.05:0);let mythic=0;for(let seed=0;seed<10000;seed++){if(rollRelic(seed,0,0,{abyssFloor:80}).tier===5)mythic++;assert.notEqual(rollRelic(seed,0,0,{abyssFloor:79}).tier,5);}assert(mythic>430&&mythic<570);
});
test('Campaign unlocks sequentially through 18, preserves introductory mechanics, and grants Abyss only after 18',()=>{const p=newProgress();assert.equal(CHAPTERS.length,18);assert.throws(()=>newAbyssRun(p,1));for(let floor=1;floor<=18;floor++){const config=chapterConfig(floor);assert.equal(config.enemyLevel,floor<8?1:floor<13?2:3);if(floor<=7){assert.equal(config.spells.includes(0),floor>=2);assert.equal(config.spells.includes(1),floor>=4);assert.equal(config.traps,floor>=5);}advanceJourney(p,{floor,runMode:'normal',elapsed:50,parTime:100,damageTaken:0},true);assert.equal(p.floor,Math.min(18,floor+1));assert.equal(!!p.abyss.unlocked,floor===18);}assert(newAbyssRun(p,1));assert(validProgress(p));});
test('All 99 floors have connected layouts, three reachable seals, Lv3–10 enemies, and no collapse',()=>{for(let f=1;f<=99;f++){c.generateStage(f*9187,18,1,false,{abyssFloor:f});assert.equal(c.stageInfo.relics.length,3);assert.equal(c.stageInfo.config.collapse,false);assert(c.cells.every(i=>c.distances[i]>=0));const enemies=enemyPlan();assert.equal(enemies.length,floorRules(f).initial);assert(enemies.every(e=>e.level===enemyLevelForFloor(f,{endless:true})&&e.maxHp>0&&Number.isFinite(e.levelDamage)));assert.equal(enemies.some(e=>e.kind===5),[10,20,30,40,60,70,80,98].includes(f));assert.equal(c.stageInfo.config.rules.chest,f%5===0||f===99);}assert.equal(enemyLevelForFloor(99,{endless:true}),10);});
test('All spawn paths enforce the 20-live cap; natural reinforcements use hidden distant cells and wait 60s',()=>{c.generateStage(814,18,1,false,{abyssFloor:35,route:'hunt'});const enemies=enemyPlan(15),p={...c.START},rules={...floorRules(1)},clock={seconds:0};assert.equal(aliveCount(enemies),20);assert.equal(spawnDue(clock,60,rules,enemies),0);enemies.slice(0,5).forEach(e=>e.dead=true);assert.equal(spawnDue(clock,59,rules,enemies),0);assert.equal(spawnDue(clock,1,rules,enemies),1);const added=naturalSpawn(enemies,p,30,random(142));assert(added.length>0);assert(aliveCount(enemies)<=20);for(const e of added){assert(Math.hypot(e.x-p.x,e.z-p.z)>16);assert(!c.lineOfSight(p.x,p.z,e.x,e.z));assert(c.canStand(e.x,e.z));}spawnTrapEnemies(enemies,enemies.at(-1),10);assert(aliveCount(enemies)<=20);});
test('Gate transitions, suspension and consumption preserve loot exactly; return settles once and death loses all run loot',()=>{const p=unlocked(),r=prepareRun(p);r.caches=[{seed:99,quality:2,abyssFloor:5,source:'chest'}];r.bag=1200;assert(suspendAbyss(p,r));assert(validProgress(p));const loaded=migrateProgress(JSON.parse(JSON.stringify(p))),restored=consumeCheckpoint(loaded);assert.equal(loaded.abyss.checkpoint,null);assert.equal(consumeCheckpoint(loaded),null);assert.deepEqual(restored.caches,r.caches);assert(nextAbyssFloor(restored));assert.equal(restored.floor,2);assert(!gateUnlocked(restored));assert(!nextAbyssFloor(restored));assert(!suspendAbyss(loaded,restored));restored.seals=3;clearAbyssFloor(restored);assert.equal(settleAbyss(loaded,restored,true).kept,1);assert.equal(loaded.totalBank,1200);assert.equal(loaded.caches.length,1);assert(settleAbyss(loaded,restored,true).duplicate);const doomed=prepareRun(loaded);doomed.id+='x';doomed.caches=[{seed:1,quality:2}];doomed.bag=9999;settleAbyss(loaded,doomed,false);assert.equal(loaded.totalBank,1200);assert.equal(loaded.caches.length,1);assert(validProgress(loaded));});
test('99F returns unlock mutators and chest/boss reward claims cannot repeat',()=>{const p=unlocked(),r=prepareRun(p);r.floor=99;const chest=floorRewardToken(r),boss=floorRewardToken(r,'boss');assert(chest.mythic);assert.equal(boss,null);assert.equal(floorRewardToken(r),null);assert(!nextAbyssFloor(r));r.caches=[chest];settleAbyss(p,r,true);assert(p.abyss.cleared99);assert.equal(p.abyss.bestFloor,99);const next=newAbyssRun(p,5,['wrath','famine']);assert.equal(next.mutators.length,2);assert(floorRules(99,next).scoreMultiplier>1);assert(validProgress(p));});
test('Excavation stays at 0–2, two is uncommon, and deeper rewards improve at the requested thresholds',()=>{const counts=[0,0,0],r=random(1788);for(let i=0;i<10000;i++)counts[excavationCount(r)]++;assert(counts[2]/10000>.07&&counts[2]/10000<.13);assert(counts[0]+counts[1]>8500);for(let f=1;f<=99;f++){c.generateStage(f*377,18,1,false,{abyssFloor:f});assert(expeditionPlan().veins.length<=2);}let previous=0;for(const f of [10,30,50,70,90]){const table=depthLoot(f);assert(table.powerDepth>previous);previous=table.powerDepth;assert(table.abyss>0);}assert(depthLoot(99).legend>depthLoot(10).legend);});
test('Normal gacha and excavation legendary chance stays about 1%; Mythic never appears in ordinary gacha',()=>{for(const quality of [0,1,2]){let legend=0;for(let seed=0;seed<20000;seed++){const item=rollRelic(seed,quality);assert(item.tier<=3);assert(!RELICS[item.type].exclusive);if(item.tier===3)legend++;}assert(legend>150&&legend<250,quality+': '+legend);}assert.equal(rarityOdds(0,9)[3],.01);});
test('Depth gear and Mythic have valid persistent powers; batch appraisal keeps guaranteed rare results and never overfills',()=>{const p=unlocked();for(let n=0;n<70;n++)p.caches.push({seed:n,quality:2,abyssFloor:99,source:'chest',...(n%10===0?{mythic:true}:{})});const count=p.caches.length,result=appraiseAll(p);assert.equal(result.results.length,count);assert(p.inventory.filter(i=>i.tier===5).length>=7);assert(p.inventory.some(i=>i.tier===4));assert(p.inventory.every(i=>i.rollA>=85));assert(validProgress(p));for(const r of ABYSS_GEAR){const item=gear(r.key,19);assert(item.type>=21);assert.equal(item.tier,r.mythic?5:4);p.inventory=[item];p.equipped=['','',''];p.equipped[r.slot]=item.id;const s=loadoutStats(p);for(const [k,v] of Object.entries(s))if(typeof v==='number')assert(Number.isFinite(v),r.key+': '+k);assert(r.powers.every(k=>s.powers.includes(k)));if(r.slot===0)assert(relicDescription(item).includes('全攻撃魔法 ×'+s.spellMultiplier));assert(validProgress(p));}});
test('Build-changing effects alter damage, protection, MP, light, revival and bounded floor boons',()=>{const p={hp:100,mp:60,light:100,lightMax:100,elapsed:20,nearEnemies:1,effectState:{}},e={id:1,hp:100,maxHp:100,kind:0,level:7};let s=effectStats({...loadoutStats(newProgress()),powers:['pristine','barrier','leech','devourlight','cycle'],curses:[]});assert.equal(strikeMultiplier(s,p,e,0,4,0),2);assert.equal(damageEffects(s,p,30,()=>1).damage,10);p.hp=50;p.light=40;killEffects(s,p,e);assert.equal(p.hp,55);assert.equal(p.light,43);s=effectStats({...loadoutStats(newProgress()),powers:['reincarnation'],curses:[]});p.hp=0;assert(reviveEffects(s,p));assert.equal(p.hp,s.maxHp);assert.equal(p.light,100);assert(!reviveEffects(s,p));const boosted=runtimeStats(loadoutStats(newProgress()),{floor:99,boons:Array(60).fill('bolt')});assert(boosted.boltBonus<=2.4);});
test('Three equipped powers awaken supernova; hidden synergies stay secret until actually equipped',()=>{const p=unlocked();p.inventory=[gear('blast',1),gear('corpse',2),gear('chain',3)];p.equipped=p.inventory.map(i=>i.id);const fresh=discoverLoadout(p);assert(fresh.some(s=>s.key==='supernova'));assert(loadoutStats(p).synergies.includes('supernova'));assert.equal(synergyStatus(p).find(s=>s.key==='supernova').count,3);assert(codexEntries(p,'equipment').some(e=>!e.found));const hidden=codexEntries(p,'synergies').find(e=>e.id==='eventhorizon');assert.equal(hidden.name,'未知の共鳴');assert.equal(codexEntries(p,'synergies').filter(e=>e.discovered).length,1);assert(!hidden.effect.includes('跳弾'));assert(validProgress(p));});
test('Salvage respects favorites/equipped items; upgrades and locked rerolls spend shards and preserve the fixed affix',()=>{const p=unlocked(),i=gear('blast');p.inventory=[i];p.shards=100;i.favorite=true;assert(workshop(p,i.id,'salvage').error);i.favorite=false;p.equipped[0]=i.id;assert(workshop(p,i.id,'salvage').error);const a=i.a,roll=i.rollA,powers=[...i.extraPowers];assert(!workshop(p,i.id,'reroll',421,true).error);assert.equal(i.a,a);assert.equal(i.rollA,roll);assert.deepEqual(i.extraPowers,powers);assert.equal(p.shards,80);for(let n=0;n<3;n++)assert(!workshop(p,i.id,'upgrade').error);assert.equal(i.upgrade,3);p.equipped[0]='';const before=p.shards;assert(!workshop(p,i.id,'salvage').error);assert.equal(p.shards,before+12);assert(validProgress(p));});
test('Eater evolves at 100 Lv7 kills, and codex reveals actual acquired items without exposing undiscovered names',()=>{const p=unlocked(),i=gear('eater');p.inventory=[i];p.equipped[0]=i.id;for(let n=0;n<99;n++)assert.equal(evolutionProgress(p,{level:7}).length,0);assert(!i.evolved);assert.equal(evolutionProgress(p,{level:6}).length,0);assert.equal(evolutionProgress(p,{level:10}).length,1);assert(i.evolved);assert(loadoutStats(p).powers.includes('eaterking'));discoverLoadout(p);assert(p.codex.evolutions.includes('eater'));assert.equal(codexEntries(p,'equipment').find(e=>e.id===i.type).name,'深淵王喰らい');for(const type of TRAP_TYPES)discover(p,'traps',type.key);assert.equal(codexEntries(p,'traps').filter(e=>e.found).length,8);assert(validProgress(p));});
test('Events have payable risks and floor branches/curses increase both pressure and reward',()=>{const p=unlocked(),r=prepareRun(p),s=loadoutStats(p);assert(applyEvent(r,{id:'merchant'},s).error);const ev={id:'vault',used:false},reward=applyEvent(r,ev,s);assert.equal(reward.spawn,2);assert(reward.token.minTier>=3);assert(applyEvent(r,ev,s).error);const hunt=floorRules(35,{route:'hunt'}),normal=floorRules(35);assert(hunt.initial>normal.initial&&hunt.initial<=20);assert(hunt.quality>normal.quality);assert(floorRules(20).light>1);assert.equal(floorRules(40).spawnInterval,30);r.hp=20;r.bag=600;r.mutators=['famine'];applyEvent(r,{id:'merchant'},s);assert.equal(r.hp,60);r.hp=20;applyEvent(r,{id:'spring'},{...s,normalHeal:0});assert.equal(r.hp,20);const leech=runtimeStats(effectStats({...s,powers:['leech']}),r),fighter={hp:20,light:100,lightMax:100,elapsed:10};killEffects(leech,fighter,{level:3});assert.equal(fighter.hp,22.5);});
test('Legacy v7 saves preserve bank, equipment and stars; malformed checkpoints and powers are rejected',()=>{const old={...newProgress(),format:7,catalog:[3*4+2],totalBank:40000,floor:8,chapterStars:{'7':3},inventory:[rollRelic(718)],caches:[{seed:1,quality:2}]};delete old.abyss;delete old.codex;delete old.shards;const p=migrateProgress(old);assert.equal(p.totalBank,old.totalBank);assert(p.codex.equipment.includes(3));assert.equal(old.codex,undefined);assert.deepEqual(p.inventory,old.inventory);assert.deepEqual(p.caches,old.caches);assert.equal(p.abyss.unlocked,false);assert(validProgress(p));assert(!validProgress({...p,abyss:{...p.abyss,checkpoint:{floor:101}}}));const bad=gear('blast');bad.extraPowers=['invented'];assert(!validProgress({...p,inventory:[bad]}));});
console.log(passed+' Abyss progression, economics, gear and persistence checks passed.');
