// Optional real-browser smoke: npm install --no-save playwright@1.62.1; npx playwright install chromium
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
const {chromium}=await import('playwright');
const dataDir=await mkdtemp(join(tmpdir(),'maze-browser-')),port=19000+process.pid%20000,base='http://127.0.0.1:'+port;
const server=spawn(process.execPath,['standalone/server.mjs'],{env:{...process.env,PORT:String(port),LIGHT_MAZE_DATA_DIR:dataDir},stdio:'ignore'});let browser,page;const errors=[];
try{
 for(let n=0;n<60;n++){try{if((await fetch(base)).ok)break;}catch{}await delay(100);}
 browser=await chromium.launch({args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});page=await context.newPage();
 page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.stack||e.message);});page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Game frame'))errors.push(m.text());});
 await page.addInitScript(()=>localStorage.setItem('light-maze-settings',JSON.stringify({quality:'low',reduced:true,sound:false})));
 // Test-only hook is inserted by request interception; no debug API ships in public/game.js.
 await page.route('**/game.js*',async route=>{const res=await route.fetch();await route.fulfill({response:res,body:(await res.text())+'\nwindow.__mazeTest={get state(){return state},get progress(){return progress},get world(){return world},get enemies(){return enemies},get relics(){return relics},get run(){return abyssRun},get sound(){return sound},get save(){return save},startRun,finish,beginAbyss,useAbyssGate,takeSeal,handleCombat,addCache,persist};'});});
 const resumeRenderPause=async()=>{if(await page.locator('#pause-dialog[open]').count()){console.log('Resuming software-renderer safety pause:',await page.locator('#pause-reason').textContent());await page.locator('#resume').click();}};
 await page.goto(base);await page.waitForFunction(()=>window.__mazeTest&&document.querySelector('#start')&&!document.querySelector('#start').disabled);await mkdir('test-results/browser',{recursive:true});await page.screenshot({path:'test-results/browser/home.png'});
 await page.locator('#start').click();await page.waitForSelector('#lesson-dialog[open]');const time=await page.evaluate(()=>__mazeTest.state.elapsed);await delay(300);assert.equal(await page.evaluate(()=>__mazeTest.state.elapsed),time);
 await page.locator('#lesson-ok').click();await page.waitForFunction(()=>!__mazeTest.state.paused);
 const initial=await page.evaluate(()=>({x:__mazeTest.state.x,z:__mazeTest.state.z,yaw:__mazeTest.state.yaw})),cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:75,y:550,id:1},{x:320,y:530,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:75,y:490,id:1},{x:280,y:530,id:2}]});await delay(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const moved=await page.evaluate(()=>({x:__mazeTest.state.x,z:__mazeTest.state.z,yaw:__mazeTest.state.yaw}));assert(Math.hypot(moved.x-initial.x,moved.z-initial.z)>.01);assert(Math.abs(moved.yaw-initial.yaw)>.02);
 await resumeRenderPause();await page.screenshot({path:'test-results/browser/chapter1.png'});if(await page.locator('#pause-dialog[open]').count())await page.locator('#abandon').click();else await page.evaluate(()=>__mazeTest.finish(false));await page.waitForFunction(()=>__mazeTest.state.mode==='result');
 await resumeRenderPause();await page.evaluate(async()=>{const p=__mazeTest.progress;p.floor=18;p.chapterStars['18']=1;p.abyss.unlocked=true;p.totalBank+=100000;p.hintsSeen.push('abyss-intro','traps-v10','abyss-spawn');await __mazeTest.persist(true);await __mazeTest.beginAbyss(false,[]);});await page.waitForFunction(()=>__mazeTest.state.runMode==='abyss'&&__mazeTest.state.mode==='play');
 const defeat=async()=>page.evaluate(async()=>{const {hurtEnemy}=await import('/enemies.js');for(const e of __mazeTest.enemies.filter(e=>e.guardSeal!==null))__mazeTest.handleCombat(hurtEnemy(e,1e9));for(const r of __mazeTest.relics)__mazeTest.takeSeal(r);});
 await resumeRenderPause();await defeat();await page.evaluate(()=>__mazeTest.useAbyssGate('next','hunt'));await page.waitForFunction(()=>__mazeTest.run.floor===2);assert.equal(await page.evaluate(()=>__mazeTest.state.seals),0);await resumeRenderPause();await page.screenshot({path:'test-results/browser/abyss.png'});
 await resumeRenderPause();await defeat();await page.evaluate(()=>{__mazeTest.addCache(47,2,{abyssFloor:50,mythic:true,source:'chest'});__mazeTest.progress.hintsSeen.push('abyss-suspend');});await page.evaluate(()=>__mazeTest.useAbyssGate('suspend'));await page.waitForFunction(()=>__mazeTest.state.mode==='menu');await page.reload();await page.waitForFunction(()=>__mazeTest&&document.querySelector('#start')&&!document.querySelector('#start').disabled);assert.equal(await page.evaluate(()=>__mazeTest.progress.abyss.checkpoint.floor),2);
 await page.evaluate(()=>__mazeTest.beginAbyss(true,[]));await page.waitForSelector('#abyss-gate-dialog[open]');await page.locator('[data-gate="return"]').click();await page.waitForFunction(()=>__mazeTest.state.mode==='result');await page.locator('#result-camp').click();await page.evaluate(()=>{window.__revealPhases=[];new MutationObserver(()=>{const el=document.querySelector('#ritual-stage');if(!el)return;const phase=el.dataset.phase,text=el.textContent;if(!__revealPhases.some(e=>e.phase===phase))__revealPhases.push({phase,text,at:performance.now()});}).observe(document.querySelector('#appraisal-result'),{attributes:true,childList:true,subtree:true});});await page.locator('#appraise-all').click();await page.waitForSelector('#skip-reveal');await page.waitForFunction(()=>window.__revealPhases?.some(e=>e.phase==='promise'&&e.text.includes('MYTHIC')));await page.screenshot({path:'test-results/browser/mythic-promise.png'});await page.waitForFunction(()=>window.__revealPhases?.some(e=>e.phase==='burst'&&e.text.includes('MYTHIC')));const phases=await page.evaluate(()=>__revealPhases);assert(phases.find(e=>e.phase==='burst').at-phases.find(e=>e.phase==='promise').at>=1200);await page.evaluate(()=>document.querySelector('#skip-reveal')?.click());await page.waitForFunction(()=>document.querySelector('#draw-detail')?.textContent.includes('MYTHIC'));await page.screenshot({path:'test-results/browser/mythic.png'});
 await page.locator('#equip-new').click();await delay(150);assert.equal(await page.locator('#avatar-canvas').evaluate(c=>c.hidden),false);await page.screenshot({path:'test-results/browser/avatar.png'});
 await page.locator('[data-close="camp-dialog"]').click();await page.waitForSelector('#lesson-dialog[open]');assert((await page.locator('#lesson-title').textContent()).includes('MYTHIC'));await page.locator('#lesson-ok').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.locator('#to-menu').click();await page.locator('#codex-open').click();assert((await page.locator('#codex-list').textContent()).includes('???'));await page.screenshot({path:'test-results/browser/codex.png'});
 const audio=await page.evaluate(async()=>{const ctx=new AudioContext(),buffer=await ctx.decodeAudioData(await(await fetch('/audio/home.mp3')).arrayBuffer());const length=buffer.duration;await ctx.close();return length;});assert(audio>1);assert.deepEqual(errors,[]);console.log('PASS Browser: 390×844 WebGL home/dungeon, simultaneous touch controls, paused lesson, floor transition, saved reload, return, all-appraisal, Mythic, avatar, codex and MP3 decoding.');
 console.log('Renderer metrics',await page.evaluate(()=>({calls:__mazeTest.world.renderer.info.render.calls,geometries:__mazeTest.world.renderer.info.memory.geometries,textures:__mazeTest.world.renderer.info.memory.textures})));
}catch(error){if(page){await mkdir('test-results/browser',{recursive:true});await page.screenshot({path:'test-results/browser/failure.png'}).catch(()=>{});console.error('Browser state:',await page.evaluate(()=>({hasHook:!!window.__mazeTest,mode:window.__mazeTest?.state.mode,paused:window.__mazeTest?.state.paused,pauseReason:document.querySelector('#pause-reason')?.textContent,save:window.__mazeTest?{status:__mazeTest.save.status,loaded:__mazeTest.save.loaded,conflict:__mazeTest.save.conflict}:null,dialogs:[...document.querySelectorAll('dialog[open]')].map(d=>d.id),loading:document.querySelector('#loading')?.textContent})).catch(()=>null));}console.error('Browser errors:',errors);throw error;}finally{await browser?.close();server.kill('SIGTERM');await rm(dataDir,{recursive:true,force:true});}
