import assert from 'node:assert/strict';
import * as c from './public/core.js';
import * as T from './public/vendor/three.module.js';
import {RevealSequence} from './public/reveal-sequence.js';
import {DIFFICULTIES,difficultyFor,clearRewardTokens,recordAttempt,recordClear,advanceJourney} from './public/journey.js';
import {RELICS,loadoutStats,rollRelic,appraisal,resolveDamage,relicDescription,affixValue,rewardPrecisionEvade,toggleFavorite,sellRelic} from './public/relics.js';
import {enemyPlan,updateEnemies,castSpell,spellCost,precisionEvade} from './public/enemies.js';
import {expeditionPlan,advanceTraps,trapTarget} from './public/expedition.js';
import {newProgress,migrateProgress} from './public/save.js';
import {validProgress} from './src/worker.js';
import {buildEquipmentAvatar,disposeAvatar} from './public/avatar.js';
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const item=(type,tier=3)=>({...rollRelic(117+type,0,0,{forcedType:type}),tier,a:0,b:1,rollA:80,rollB:80});
const equipped=items=>{const p=newProgress();p.floor=8;p.inventory=items;for(const i of items)p.equipped[RELICS[i.type].slot]=i.id;return p;};
const clock=()=>{let now=0,serial=0,jobs=[];return{get now(){return now;},schedule(fn,delay){const id=++serial;jobs.push({id,at:now+delay,fn});return id;},cancel(id){jobs=jobs.filter(j=>j.id!==id);},advance(ms){const to=now+ms;while(true){jobs.sort((a,b)=>a.at-b.at||a.id-b.id);if(!jobs.length||jobs[0].at>to)break;const j=jobs.shift();now=j.at;j.fn();}now=to;}};};
test('Ten-pull openings preserve order, hide rarity until the promise, and dwell on each legendary before the next item',()=>{
 const timer=clock(),results=[0,3,0,2,0,1,0,0,0,0].map((tier,i)=>({item:{...item(0,tier),id:String(i)}})),events=[],original=structuredClone(results),sequence=new RevealSequence(results,e=>events.push({...e,at:timer.now}),timer);sequence.start();timer.advance(100000);
 assert.deepEqual(events.filter(e=>e.phase==='burst').map(e=>e.index),Array.from({length:10},(_,i)=>i));assert.equal(events.filter(e=>e.phase==='complete').length,1);
 const leg=events.filter(e=>e.index===1),sealed=leg.find(e=>e.phase==='sealed'),promise=leg.find(e=>e.phase==='promise'),burst=leg.find(e=>e.phase==='burst');assert.equal(promise.at-sealed.at,4000);assert.equal(burst.at-sealed.at,5200);assert(events.find(e=>e.phase==='sealed'&&e.index===2).at>=burst.at+3200);assert(leg.some(e=>e.phase==='silence'));assert(events.filter(e=>['gather','sealed','charge','silence'].includes(e.phase)).every(e=>e.tier===undefined));assert(events.filter(e=>e.phase==='promise').every(e=>results[e.index].item.tier>=2));assert.deepEqual(results,original);
 const t=clock(),events2=[],skip=new RevealSequence(results,e=>events2.push(e),t);skip.start();t.advance(1200);skip.finish();skip.finish();t.advance(100000);assert.equal(events2.filter(e=>e.phase==='complete').length,1);assert(!events2.some(e=>e.phase==='burst'));assert.deepEqual(results,original);
});
test('Every grade increases pressure; hard and abyss use substantially stronger, faster attacks while daily remains fixed',()=>{
 for(let floor=1;floor<=6;floor++){c.generateStage(811,floor);const d=c.stageInfo.config.difficulty,expected=floor<=2?DIFFICULTIES[0]:DIFFICULTIES[1];assert.equal(d,expected);assert(d.hp>1&&d.damage>1&&d.speed>1);}
 const sample=(floor,daily=false)=>{c.generateStage(811,floor,1,daily);const e=enemyPlan().find(e=>e.kind===2),p={x:e.x,z:e.z+.8,yaw:Math.PI,pitch:0,light:0};let windup=0,hit;for(let i=0;i<100&&!hit;i++){const {events}=updateEnemies([e],p,.025);if(events.some(a=>a.type==='windup'))windup=e.windup;hit=events.find(a=>a.type==='hit');}assert(hit);return{hp:e.maxHp,damage:hit.damage,windup};};
 const base=sample(8,true),hard=sample(7),abyss=sample(8);assert(abyss.hp>base.hp*2.4);assert(abyss.damage>base.damage*2);assert(abyss.windup<base.windup*.6);assert(hard.hp>base.hp*1.4&&hard.hp<abyss.hp);assert(hard.damage>base.damage&&hard.damage<abyss.damage);
 assert.deepEqual(DIFFICULTIES.map(d=>d.target),['80〜100%','50%','20%','5%']);
});
test('An engaged boss crosses its room boundary, retaliates at range, and enters a faster second phase',()=>{
 c.generateStage(811,7);let boss=enemyPlan().find(e=>e.kind===5),room=c.rooms[boss.homeRoom],field=c.distanceField(c.indexAt(boss.x,boss.z)),target=[...c.cells].filter(i=>field[i]>12&&c.distances[i]>5).sort((a,b)=>field[b]-field[a])[0],player={x:target%c.W*c.S,z:Math.floor(target/c.W)*c.S,yaw:0,pitch:0,light:100,hp:100,mp:60,seals:0,count:0,runMode:'normal',explored:new Set(c.cells)};boss.memory=60;boss.attackCooldown=999;let farthest=0;for(let i=0;i<1200;i++){updateEnemies([boss],player,.05);farthest=Math.max(farthest,Math.hypot(boss.x-room.x*c.S,boss.z-room.z*c.S));}assert(farthest>14,'boss must pursue beyond the former leash');assert(Math.hypot(boss.x-player.x,boss.z-player.z)<.2);
 c.generateStage(812,7);boss=enemyPlan().find(e=>e.kind===5);room=c.rooms[boss.homeRoom];const tile=room.tiles.map(i=>({i,d:Math.hypot(i%c.W*c.S-boss.x,Math.floor(i/c.W)*c.S-boss.z)})).filter(v=>v.d>3.6&&v.d<12).sort((a,b)=>b.d-a.d)[0];player={x:tile.i%c.W*c.S,z:Math.floor(tile.i/c.W)*c.S,yaw:0,pitch:0,light:100,hp:100,mp:60,seals:0,count:0,runMode:'normal',explored:new Set(c.cells)};let result=updateEnemies([boss],player,.01);assert(result.events.some(e=>e.type==='windup'&&e.attackKind==='rift'));result=updateEnemies([boss],player,boss.windup+.02);assert(result.events.some(e=>e.type==='hit'&&e.cause==='rift'));assert(result.events.some(e=>e.type==='impact'&&e.ranged));boss.hp=Math.floor(boss.maxHp*.4);result=updateEnemies([boss],player,.01);assert(result.events.some(e=>e.type==='enraged'));assert(boss.enraged);
});
test('Instant abyss traps fire on contact once, can be identified before stepping on them, and can be aimed at from safe ground',()=>{
 c.generateStage(210,8);const plan=expeditionPlan(),instant=plan.traps.find(t=>t.instant);assert(instant);assert.equal(instant.fuse,0);assert.equal(instant.damage,72);
 const player={x:instant.x,z:instant.z+1.5,yaw:0,pitch:Math.atan2(-1.45,1.5)};assert.equal(trapTarget([instant],player),instant);assert.equal(advanceTraps([instant],player,.02).length,0);
 player.z=instant.z;const events=advanceTraps([instant],player,.02);assert(events.some(e=>e.type==='burst'&&e.hit&&e.damage===72));assert.equal(advanceTraps([instant],player,2).length,0);
 const slow={x:0,z:0,timer:-1,fuse:.9,spent:false,damage:19};assert(!advanceTraps([slow],{x:0,z:0},.1).some(e=>e.type==='burst'));const evaded=advanceTraps([slow],{x:3,z:0},1);assert(evaded.some(e=>e.type==='burst'&&!e.hit));
});
test('Legendary power changes actual combat: more than triple a common dawn bolt, stronger affixes, protection and faster casting',()=>{
 c.generateStage(31,6);const origin=enemyPlan()[0],p={x:origin.x,z:origin.z+.8,yaw:0,pitch:0,hp:100,mp:160},target=()=>({...origin,kind:0,hp:10000,maxHp:10000,recovery:0,stun:0,windup:0});
 const common=loadoutStats(equipped([item(0,0)])),legend=loadoutStats(equipped([item(0,3)])),a=castSpell(0,[target()],{...p},common,()=>1).events[0].damage,b=castSpell(0,[target()],{...p},legend,()=>1).events[0].damage;assert(b>a*3);assert(affixValue(item(0,3))>affixValue(item(0,0))*3);assert(relicDescription(item(0,3)).includes('+90%'));assert.equal(loadoutStats(equipped([item(16)])).boltCooldown,.52);
 const armor=loadoutStats(equipped([item(14)]));assert(resolveDamage(80,'slam',armor,200).damage<resolveDamage(80,'shadow',armor,200).damage*.45);assert(armor.maxHp>100);assert.deepEqual(loadoutStats(equipped([item(18),item(19),item(20)]),true),loadoutStats(newProgress()));
});
test('Abyss items reward skill: weak hits refund MP once per cast and phoenix armor survives only one fatal blow',()=>{
 c.generateStage(71,8);const stats=loadoutStats(equipped([item(18),item(19),item(20)])),origin=enemyPlan()[0],target={...origin,kind:2,hp:9999,maxHp:9999,recovery:1,stun:0,windup:0},p={x:origin.x,z:origin.z+.8,yaw:0,pitch:0,hp:stats.maxHp,mp:40};const before=p.mp,hit=castSpell(0,[target],p,stats,()=>1);assert(hit.events[0].weak);assert.equal(hit.recovered,3);assert.equal(p.mp,before-spellCost(0,stats)+3);
 const first=resolveDamage(999,'shadow',stats,stats.maxHp);assert(first.revived);assert.equal(first.hp,Math.ceil(stats.maxHp*.35));const second=resolveDamage(999,'shadow',stats,first.hp,true);assert(!second.revived);assert.equal(second.hp,0);assert.equal(stats.dodgeLight,4);const evader={elapsed:10,light:20,mp:20};assert.equal(rewardPrecisionEvade(evader,stats,{precision:false},100),null);assert.deepEqual(rewardPrecisionEvade(evader,stats,{precision:true},100),{light:4,mp:3});assert.equal(rewardPrecisionEvade(evader,stats,{precision:true},100),null);evader.elapsed+=4;assert(rewardPrecisionEvade(evader,stats,{precision:true},100));assert.equal(evader.light,28);assert(!precisionEvade({attackAim:{x:0,z:0}},{x:0,z:0}));assert(precisionEvade({attackAim:{x:0,z:0}},{x:1.1,z:0}));assert(!precisionEvade({attackAim:{x:0,z:0}},{x:10,z:0}));
});
test('Abyss clears guarantee two high-quality legendaries, every fifth level gives three, and exclusive equipment never enters ordinary gacha',()=>{
 for(let level=1;level<=15;level++){const run={runMode:'normal',floor:8,trialLevel:level,seed:level*198},tokens=clearRewardTokens(run),p=newProgress();p.floor=8;p.caches=tokens;assert.equal(tokens.length,level%5===0?3:2);const n=tokens.length;for(let i=0;i<n;i++){const r=appraisal(p,123,{cache:true});assert.equal(r.item.tier,3);assert(r.item.rollA>=70&&r.item.rollB>=70);}assert(p.inventory.some(i=>RELICS[i.type].exclusive));assert(validProgress(p));assert.deepEqual(clearRewardTokens({...run,runMode:'daily'}),[]);}
 const high=clearRewardTokens({floor:7,runMode:'normal',seed:3});assert.equal(high.length,2);assert(high.every(t=>t.minTier===2&&t.minRoll===40));for(let i=0;i<3000;i++)assert(!RELICS[rollRelic(i,2,9).type].exclusive);
});
test('Old equipment and currency survive migration; difficulty rates count real starts and clears and do not decrease unlocked trial levels on replays',()=>{
 const old={...equipped([item(0,3)]),format:4,totalBank:41000,trialLevel:7,bestTrial:6,caches:[{seed:111,quality:2}],chapterStars:{'7':2}};delete old.difficultyStats;const p=migrateProgress(old);assert.equal(p.format,7);assert.deepEqual(p.inventory,old.inventory);assert(p.inventory.every(i=>i.favorite===false));assert.deepEqual(p.equipped,old.equipped);assert.equal(p.totalBank,41000);assert.deepEqual(p.caches,old.caches);recordAttempt(p,8);recordAttempt(p,8);recordClear(p,8);assert.deepEqual(p.difficultyStats.abyss,{attempts:2,clears:1});advanceJourney(p,{floor:8,trialLevel:1,runMode:'normal',damageTaken:0,elapsed:100,parTime:100},true);assert.equal(p.trialLevel,7);assert.equal(p.bestTrial,6);assert(validProgress(p));assert(!validProgress({...p,difficultyStats:{abyss:{attempts:1,clears:2}}}));
});
test('The humanoid rig keeps adult proportions and batches detailed armor into a small number of draws with finite geometry',()=>{
 for(const gear of [[item(0,0),item(12,0)],[item(18),item(19),item(20)]]){const avatar=buildEquipmentAvatar(equipped(gear)),bounds=new T.Box3().setFromObject(avatar.group);assert(avatar.group.userData.humanHeight/avatar.group.userData.headHeight>7);assert(bounds.max.y<3.5&&bounds.min.y>-.1);let meshes=0,vertices=0;avatar.group.traverse(o=>{if(o.isMesh){meshes++;const a=o.geometry.getAttribute('position');vertices+=a.count;assert(Array.from(a.array).every(Number.isFinite));}});assert(meshes<=25);assert(vertices<150000);assert.equal(avatar.group.userData.staffType,gear[0].type);disposeAvatar(avatar.group);}
});
console.log(`${passed} ceremony, difficulty, legendary equipment, migration and humanoid checks passed.`);
