// Lifecycle tests use DOM/renderer doubles, not a browser or a GPU.
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as core from './public/core.js';
import * as T from './public/vendor/three.module.js';
import {World} from './public/world.js';
import {enemyPlan,hurtEnemy,enemyDrops} from './public/enemies.js';
import {expeditionPlan} from './public/expedition.js';
import {rollRelic,CACHE_LIMIT} from './public/relics.js';
import {newProgress} from './public/save.js';
import {validProgress} from './src/worker.js';

const nodes=new Map(),all=[],timers=[];
class Node{
 constructor(tag='div',id=''){this.tagName=tag;this.id=id;this.dataset={};this.listeners={};this.style={setProperty(k,v){this[k]=v;}};this.hidden=false;this.disabled=false;this.open=false;this.value='';this.textContent='';const classes=new Set();this.classList={add:(...c)=>c.forEach(x=>classes.add(x)),remove:(...c)=>c.forEach(x=>classes.delete(x)),toggle:(c,on)=>{if(on??!classes.has(c))classes.add(c);else classes.delete(c);},contains:c=>classes.has(c)};if(id)nodes.set(id,this);all.push(this);}
 set innerHTML(html){this._html=html;parse(html);}get innerHTML(){return this._html||'';}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}setAttribute(){}append(){}replaceChildren(){}remove(){}setPointerCapture(){}
 closest(selector){return (selector.includes('button')&&this.tagName==='button')||(selector==='[data-chapter]'&&this.dataset.chapter)?this:null;}
 querySelector(selector){return all.find(n=>selector==='.ritual'&&n._ritual)||null;}hasPointerCapture(){return false;}releasePointerCapture(){}
 showModal(){this.open=true;}close(){this.open=false;this.emit('close');}
 emit(name,target=this){for(const fn of this.listeners[name]||[])fn({target,currentTarget:this,preventDefault(){}});}
 getContext(){return new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});}
}
function parse(html){for(const match of html.matchAll(/<(\w+)\b([^>]*)>/g)){const attrs=match[2],id=attrs.match(/\bid="([^"]+)"/)?.[1];if(id&&nodes.has(id))continue;const n=new Node(match[1],id);for(const a of attrs.matchAll(/data-([\w-]+)="([^"]*)"/g))n.dataset[a[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=a[2];}}
parse(await readFile(new URL('./public/index.html',import.meta.url),'utf8'));
const initialIds=new Set(nodes.keys());
globalThis.document={body:new Node('body'),hidden:false,getElementById:id=>{if(!nodes.has(id))throw Error('Missing DOM target '+id);return nodes.get(id);},createElement:tag=>new Node(tag),querySelectorAll:selector=>{const attr=selector.match(/\[data-([\w-]+)\]/)?.[1]?.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return all.filter(n=>attr&&attr in n.dataset);},querySelector:()=>all.find(n=>n.tagName==='dialog'&&n.open),addEventListener(){}};
globalThis.window={addEventListener(){}};globalThis.matchMedia=()=>({matches:false});globalThis.localStorage={getItem:()=>null,setItem(){},removeItem(){}};globalThis.requestAnimationFrame=()=>0;globalThis.cancelAnimationFrame=()=>{};globalThis.innerWidth=390;globalThis.innerHeight=844;
globalThis.setTimeout=fn=>(timers.push(fn),timers.length);globalThis.clearTimeout=()=>{};
let stored=newProgress();stored.totalBank=20000;let writes=0;
globalThis.fetch=async(path,options={})=>{assert.equal(path,'/api/progress');if(options.method==='PUT'){const p=JSON.parse(options.body);assert(validProgress(p),'Lifecycle emitted invalid save');stored=p;writes++;}return new Response(JSON.stringify(options.method==='PUT'?{ok:true}:stored),{headers:{'x-save-revision':'r'+writes}});};
const data=source=>'data:text/javascript;base64,'+Buffer.from(source).toString('base64');
const worldStub=data(`import {canStand} from '${new URL('./public/core.js',import.meta.url)}';export class World{constructor(){this.uniforms={uRevealPulse:{value:0}};this.qualityScale=1;}setLoot(){}resetLevel(){}setEquipment(){}spawnDrops(){}spawnEnemies(){}wave(){}burst(){}castBeam(){}hitImpact(){}resize(){}render(){}canMove(x,z){return canStand(x,z);}}`);
const soundStub=data('export class Sound{start(){}note(){}chime(){}chain(){}legendary(){}bank(){}haptic(){}reveal(){}tick(){}}');
const avatarStub=data('export class AvatarPreview{constructor(){}set(){}close(){}}');let campSource=await readFile(new URL('./public/camp.js',import.meta.url),'utf8');campSource=campSource.replace("'./avatar.js'",JSON.stringify(avatarStub)).replace(/from '(\.\/[^']+)'/g,(_,path)=>'from '+JSON.stringify(new URL(path,new URL('./public/camp.js',import.meta.url)).href));
let source=await readFile(new URL('./public/game.js',import.meta.url),'utf8');source=source.replace("'./camp.js'",JSON.stringify(data(campSource)));
source=source.replace("'./world.js'",JSON.stringify(worldStub)).replace("'./audio.js'",JSON.stringify(soundStub));
source=source.replace(/from '(\.\/[^']+)'/g,(_,path)=>'from '+JSON.stringify(new URL(path,new URL('./public/game.js',import.meta.url)).href));
source+='\nexport const testApi={get state(){return state},get progress(){return progress},get stats(){return stats},get expedition(){return expedition},get enemies(){return enemies},get relics(){return relics},get drops(){return drops},get items(){return items},get orbs(){return orbs},get input(){return input},updateDrops,handleCombat,startRun,simulate,finish,useMagic,useFlash,selectSpell,takeDamage,takeSeal,pickup,updateMining,addCache,setMineHeld(v){mineHeld=v},get save(){return save},get abyssRun(){return abyssRun},get abyssChest(){return abyssChest},beginAbyss,useAbyssGate,tickAbyss,abyssUI};';
const {testApi:a}=await import(data(source));for(let i=0;i<12;i++)await Promise.resolve();assert(a.save.loaded);assert(initialIds.has('cast-action'));

const flush=async()=>{for(let turn=0;turn<40;turn++){for(const fn of timers.splice(0))fn();for(let i=0;i<16;i++)await Promise.resolve();if(!timers.length)return;}throw Error("Unsettled lifecycle timers");};
const dismissLesson=()=>{if(nodes.get('lesson-dialog').open)nodes.get('lesson-dialog').close();};
const choose=floor=>{nodes.get('stage-open').emit('click');const button=all.findLast(n=>Number(n.dataset.chapter)===floor);assert(button);nodes.get('stages-dialog').emit('click',button);};
const defeatGuards=()=>{for(const e of a.enemies.filter(e=>e.guardSeal!==null&&!e.dead))a.handleCombat(hurtEnemy(e,99999));for(const r of a.relics)a.takeSeal(r);};
a.startRun();assert.equal(a.state.floor,1);assert(a.state.paused);a.simulate(3);assert.equal(a.state.elapsed,0);assert(nodes.get('cast-action').hidden);assert(nodes.get('vitals').hidden);assert.equal(a.relics.length,1);assert.equal(a.enemies.length,0);dismissLesson();assert(!a.state.paused);assert(a.progress.hintsSeen.includes('chapter-1'));
// Clear the introductory seal through actual focus time and enter the exit trigger.
const firstSeal=a.relics[0];a.state.x=firstSeal.x;a.state.z=firstSeal.z+1;a.state.yaw=0;for(let i=0;i<60;i++)a.simulate(.05);assert.equal(a.state.seals,1);assert.equal(a.state.collapse,Infinity);const cash=a.progress.totalBank,bag=a.state.bag;Object.assign(a.state,core.START);for(let i=0;i<10&&a.state.mode==='play';i++)a.simulate(.05);await flush();assert.equal(a.state.mode,'result');assert.equal(a.progress.floor,2);assert.equal(a.progress.totalBank,cash+bag+1500);assert(a.progress.inventory.some(i=>i.id==='gift-1'));assert(nodes.get('result-primary').textContent.includes('★'));
// The second chapter introduces combat and requires physical collection of enemy rewards.
a.startRun();dismissLesson();assert.equal(a.state.floor,2);assert(!nodes.get('cast-action').hidden);assert(nodes.get('flash-action').hidden);for(const r of a.relics)assert.equal(a.takeSeal(r),false);assert.equal(a.state.seals,0);
const e=a.enemies[0];a.state.x=e.x;a.state.z=e.z+2;a.state.pitch=0;for(let i=0;i<100&&!e.dead;i++){a.state.yaw=Math.atan2(-(e.x-a.state.x),-(e.z-a.state.z));a.useMagic();if(!e.dead)a.simulate(.05);}assert(e.dead);assert.equal(a.state.kills,1);assert(a.drops.length);assert(a.drops.every(d=>!d.collected&&d.age===0));const loot=a.drops.find(d=>d.kind==='essence');a.state.x=loot.x;a.state.z=loot.z;a.state.light=20;a.state.mp=5;const beforeBag=a.state.bag;a.updateDrops(.25);assert.equal(a.state.light,20);a.updateDrops(.4);assert(loot.collected);assert.equal(a.state.light,32);assert.equal(a.state.mp,15);assert.equal(a.state.bag,beforeBag+80);
const light=a.state.light;a.takeDamage(20,'shadow');assert(a.state.hp<100);assert.equal(a.state.light,light);defeatGuards();a.finish(true);await flush();assert.equal(a.progress.floor,3);assert(a.progress.inventory.some(i=>i.type===12));
// Armor is equipped, but locked spells cannot be selected in earlier chapters.
a.startRun();dismissLesson();assert.equal(a.stats.moveSpeed,1.14);a.takeDamage(20,'shadow');const hurt=a.state.hp;a.selectSpell(2);a.useMagic();assert(a.state.hp>hurt);a.finish(false);await flush();
// Use the real chapter selector and camp appraisal handlers after their unlock.
a.progress.floor=4;choose(4);a.startRun();dismissLesson();assert.equal(a.state.floor,4);const v=a.expedition.veins[0];a.state.x=v.x-v.dx*1.9;a.state.z=v.z-v.dz*1.9;a.state.yaw=Math.atan2(-v.dx,-v.dz);a.state.pitch=0;a.state.move=0;a.setMineHeld(true);for(let i=0;i<v.layers;i++)a.updateMining(1.1);assert.equal(v.hits,v.layers);assert(a.state.caches.length>0);const cacheCount=a.state.caches.length;defeatGuards();a.finish(true);await flush();assert.equal(a.progress.floor,5);assert(a.progress.caches.length>=cacheCount);assert(a.progress.inventory.some(i=>i.type===13));
const count=a.progress.inventory.length,held=a.progress.caches.length;nodes.get('result-camp').emit('click');nodes.get('appraise-cache').emit('click');await flush();assert.equal(a.progress.inventory.length,count+1);assert.equal(a.progress.caches.length,held-1);assert(validProgress(a.progress));nodes.get('camp-dialog').close();
// Bust keeps banked gear but forfeits everything carried in this expedition.
a.startRun();dismissLesson();const savedCash=a.progress.totalBank,savedCaches=a.progress.caches.length;a.addCache(1,2);a.state.bag=9000;a.finish(false);await flush();assert.equal(a.progress.totalBank,savedCash);assert.equal(a.progress.caches.length,savedCaches);assert.equal(a.progress.floor,5);
// High campaign milestones have explicit guaranteed rewards and unlock the next chapter.
a.progress.floor=13;a.progress.trialLevel=10;choose(13);nodes.get('trial-level').value=10;nodes.get('trial-level').emit('change');const bankedBeforeTrial=a.progress.caches;const beforeAttempts=a.progress.runs;a.progress.caches=Array.from({length:CACHE_LIMIT-2},(_,i)=>({seed:i,quality:0}));a.startRun();assert.equal(a.progress.runs,beforeAttempts);assert(nodes.get('camp-dialog').open);a.progress.caches=bankedBeforeTrial;nodes.get('camp-dialog').close();a.startRun();dismissLesson();assert.equal(a.state.trialLevel,0);const trap=a.expedition.traps[0],node=core.neighbors(core.indexAt(trap.x,trap.z))[0];a.state.x=node%core.W*core.S;a.state.z=Math.floor(node/core.W)*core.S;a.state.yaw=Math.atan2(-(trap.x-a.state.x),-(trap.z-a.state.z));a.state.pitch=Math.atan2(-1.45,Math.hypot(trap.x-a.state.x,trap.z-a.state.z));const deadStates=a.enemies.map(e=>e.dead);a.enemies.forEach(e=>e.dead=true);const trapMp=a.state.mp;a.selectSpell(0);a.useMagic();assert(trap.spent);assert(a.state.mp<trapMp);assert.equal(a.state.trapsDisarmed,1);a.enemies.forEach((e,i)=>e.dead=deadStates[i]);defeatGuards();a.finish(true);await flush();assert.equal(a.progress.floor,14);assert.equal(a.progress.trialLevel,10);assert(a.progress.caches.some(c=>c.minTier===3));assert(nodes.get('result-message').textContent.includes('伝説1個'));
// A fixed daily loadout ignores armor/upgrades, and clears do not pay campaign rewards.
nodes.get('mode-daily').emit('click');a.progress.level=4;a.startRun();assert(!a.state.paused);assert.equal(a.state.lightMax,100);assert.equal(a.stats.power,0);assert.equal(a.stats.maxHp,100);assert.equal(a.stats.moveSpeed,1);assert(!a.stats.warpImmune);const seed=a.state.seed,dailyCash=a.progress.totalBank,dailyFloor=a.progress.floor,trial=a.progress.trialLevel;a.state.elapsed=145.2;a.state.bag=5000;a.addCache(2,2);defeatGuards();a.finish(true);await flush();assert.equal(a.progress.totalBank,dailyCash);assert.equal(a.progress.floor,dailyFloor);assert.equal(a.progress.trialLevel,trial);assert.equal(a.progress.dailyBests[0].time,145.2);assert(a.progress.dailyBests[0].cleared);assert.equal(nodes.get('result-primary').textContent,'145.20 秒');a.startRun();assert.equal(a.state.seed,seed);assert.equal(a.state.hp,100);assert.equal(a.drops.length,0);a.state.elapsed=150;defeatGuards();a.state.bag=900000;a.finish(true);await flush();assert.equal(a.progress.dailyBests[0].time,145.2);assert(validProgress(stored));
// Actual camp handlers: a guaranteed legendary reveals honestly, rapid taps charge once,
// and skipping the ten-pull presentation never loses any of the ten acquired items.
a.progress.caches.unshift({seed:77,quality:2,minTier:3});nodes.get('result-camp').emit('click');const legendaryBefore=a.progress.inventory.length;nodes.get('appraise-cache').emit('click');await flush();assert.equal(a.progress.inventory.length,legendaryBefore+1);assert.equal(a.progress.inventory.at(-1).tier,3);assert(nodes.get('draw-detail').innerHTML.includes('LEGENDARY'));assert.equal(nodes.get('ritual-promise').textContent,'LEGENDARY');
const drawCount=a.progress.draws,spent=a.progress.forgeSpent,inventory=a.progress.inventory.length;nodes.get('buy-ten').emit('click');nodes.get('buy-ten').emit('click');assert.equal(a.progress.draws,drawCount+10);assert.equal(a.progress.forgeSpent,spent+6000);assert.equal(a.progress.inventory.length,inventory+10);nodes.get('camp-dialog').emit('click',nodes.get('skip-reveal'));await flush();assert(nodes.get('appraisal-result').innerHTML.includes('10 RELICS REVEALED'));assert.equal(stored.inventory.length,a.progress.inventory.length);assert.equal(stored.forgeSpent,a.progress.forgeSpent);assert(validProgress(stored));nodes.get('camp-dialog').close();
console.log('PASS Real camp handlers: legendary guarantee, single-charge ten-pull, skip, and persisted results');
console.log('PASS Game lifecycle: paused tutorials, staged UI, guardians, physical loot, armor, mining, appraisal, bust, trial rewards, and daily records');

// Exercise actual game orchestration across floors, not only the pure checkpoint helpers.
a.progress.floor=18;a.progress.chapterStars['18']=1;a.progress.abyss.unlocked=true;
const dismissAll=async()=>{for(let n=0;n<12;n++){dismissLesson();await Promise.resolve();await Promise.resolve();}};
await a.beginAbyss(false,[]);await dismissAll();assert.equal(a.state.runMode,'abyss');assert.equal(a.abyssRun.floor,1);assert.equal(a.state.collapse,Infinity);for(const def of (await import('./public/abyss-rules.js')).EVENT_TYPES){a.abyssUI.event({id:def.id});assert.equal(nodes.get('abyss-event-title').textContent,def.name);assert(a.state.paused);nodes.get('abyss-event-dialog').close();}assert(!a.state.paused);a.addCache(701,2);a.state.bag=1000;defeatGuards();assert.equal(a.abyssRun.seals,3);await a.useAbyssGate('next','hunt');await dismissAll();assert.equal(a.abyssRun.floor,2);assert.equal(a.state.caches.length,1);assert.equal(a.state.bag,1000);assert.equal(a.state.seals,0);assert.equal(core.stageInfo.config.rules.route,'hunt');defeatGuards();await a.useAbyssGate('suspend');assert(nodes.get('lesson-dialog').open);await dismissAll();await a.useAbyssGate('suspend');await flush();assert.equal(a.state.mode,'menu');assert(a.progress.abyss.checkpoint);assert.equal(a.progress.abyss.checkpoint.caches.length,1);assert.equal(stored.abyss.checkpoint.floor,2);assert(validProgress(stored));
await a.beginAbyss(true,[]);await dismissAll();assert.equal(a.abyssRun.floor,2);assert.equal(a.state.seals,3);assert.equal(a.progress.abyss.checkpoint,null);assert(nodes.get('abyss-gate-dialog').open);const abyssBank=a.progress.totalBank,abyssCaches=a.progress.caches.length;await a.useAbyssGate('return');await flush();assert.equal(a.state.mode,'result');assert.equal(a.progress.totalBank,abyssBank+1000);assert.equal(a.progress.caches.length,abyssCaches+1);assert.equal(a.progress.abyss.bestFloor,2);
a.state.mode='menu';await a.beginAbyss(false,[]);await dismissAll();a.addCache(999,2);a.state.bag=8888;const bankBeforeDeath=a.progress.totalBank,cachesBeforeDeath=a.progress.caches.length;a.takeDamage(999999,'shadow');await flush();assert.equal(a.state.mode,'result');assert.equal(a.progress.totalBank,bankBeforeDeath);assert.equal(a.progress.caches.length,cachesBeforeDeath);assert.equal(a.progress.abyss.checkpoint,null);assert(validProgress(stored));
console.log('PASS Actual Abyss floor transition, paused suspension lesson, cloud checkpoint, gate resume, banking, and death loss');

// Construct real Three.js scene geometry and regenerate it without a WebGL context.
const w=Object.create(World.prototype);w.scene=new T.Scene();w.root=new T.Group();w.scene.add(w.root);w.camera=new T.PerspectiveCamera();w.elapsed=0;w.maskBytes=new Uint8Array(core.MASK*core.MASK);w.mask={needsUpdate:false};w.uniforms={uMapSize:{value:new T.Vector2()},uWaveAge:{value:10},uTime:{value:0},uPlayer:{value:new T.Vector3()},uMenu:{value:0},uMask:{value:null}};w.stone=new T.ShaderMaterial({uniforms:{uBase:{value:new T.Color()}}});w.bronze=new T.MeshBasicMaterial();w.darkmetal=new T.MeshBasicMaterial();w.glowMaterials=Array.from({length:4},()=>new T.MeshBasicMaterial());
for(const floor of [1,2,5,8,1]){core.generateStage(7193,floor);const exp=expeditionPlan(),enemies=enemyPlan(exp.omen.enemies);w.resetLevel(new core.Reveal(),core.treasurePlan(),core.orbPlan(),core.stageInfo.relics,enemies,exp);assert.equal(w.veinMeshes.length,exp.veins.length);assert.equal(w.beamFX.length,8);assert.equal(w.enemyMeshes.length,enemies.length);const state={x:enemies[0]?.x??core.START.x,z:(enemies[0]?.z??core.START.z)+3,menu:false,dark:false};w.animateActors(1,state);w.animateExpedition(.02,state);w.castBeam(state.x,state.z,state.x,state.z+2);if(enemies.length){const loot=enemyDrops(enemies[0],134);w.spawnDrops(loot);assert.equal(w.dropMeshes.length,loot.length);}assert(w.beamFX.some(b=>b.life>0));if(enemies.length){enemies[0].dead=true;w.animateActors(1,state);assert(!w.enemyMeshes[0].group.visible);}w.animateExpedition(1,state);assert(w.beamFX.every(b=>!b.mesh.visible));}
console.log('PASS Real 3D scene regeneration and spell/enemy/mining actors without renderer');
